// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package tcfirewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallFwStats struct {
	_               structs.HostLayout
	TotalPackets    uint64
	DroppedPackets  uint64
	AcceptedPackets uint64
	TcpPackets      uint64
	UdpPackets      uint64
	IcmpPackets     uint64
	OtherPackets    uint64
}

// loadFirewall returns the embedded CollectionSpec for firewall.
func loadFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewall: %w", err)
	}

	return spec, err
}

// loadFirewallObjects loads firewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallObjects
//	*firewallPrograms
//	*firewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallSpecs struct {
	firewallProgramSpecs
	firewallMapSpecs
	firewallVariableSpecs
}

// firewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallProgramSpecs struct {
	TcEgressFirewall  *ebpf.ProgramSpec `ebpf:"tc_egress_firewall"`
	TcIngressFirewall *ebpf.ProgramSpec `ebpf:"tc_ingress_firewall"`
}

// firewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallMapSpecs struct {
	AllowedIps   *ebpf.MapSpec `ebpf:"allowed_ips"`
	BlockedIps   *ebpf.MapSpec `ebpf:"blocked_ips"`
	BlockedPorts *ebpf.MapSpec `ebpf:"blocked_ports"`
	StatsMap     *ebpf.MapSpec `ebpf:"stats_map"`
}

// firewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallVariableSpecs struct {
}

// firewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallObjects struct {
	firewallPrograms
	firewallMaps
	firewallVariables
}

func (o *firewallObjects) Close() error {
	return _FirewallClose(
		&o.firewallPrograms,
		&o.firewallMaps,
	)
}

// firewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallMaps struct {
	AllowedIps   *ebpf.Map `ebpf:"allowed_ips"`
	BlockedIps   *ebpf.Map `ebpf:"blocked_ips"`
	BlockedPorts *ebpf.Map `ebpf:"blocked_ports"`
	StatsMap     *ebpf.Map `ebpf:"stats_map"`
}

func (m *firewallMaps) Close() error {
	return _FirewallClose(
		m.AllowedIps,
		m.BlockedIps,
		m.BlockedPorts,
		m.StatsMap,
	)
}

// firewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallVariables struct {
}

// firewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallPrograms struct {
	TcEgressFirewall  *ebpf.Program `ebpf:"tc_egress_firewall"`
	TcIngressFirewall *ebpf.Program `ebpf:"tc_ingress_firewall"`
}

func (p *firewallPrograms) Close() error {
	return _FirewallClose(
		p.TcEgressFirewall,
		p.TcIngressFirewall,
	)
}

func _FirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewall_x86_bpfel.o
var _FirewallBytes []byte
