// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package filterdns

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filterdnsDnsStats struct {
	_                structs.HostLayout
	TotalPackets     uint64
	DnsPackets       uint64
	DroppedPackets   uint64
	WhitelistAllowed uint64
	WhitelistDropped uint64
	BlacklistDropped uint64
}

type filterdnsFilterConfig struct {
	_        structs.HostLayout
	ListMode uint32
}

type filterdnsIpv6Addr struct {
	_  structs.HostLayout
	Hi uint64
	Lo uint64
}

// loadFilterdns returns the embedded CollectionSpec for filterdns.
func loadFilterdns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilterdnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filterdns: %w", err)
	}

	return spec, err
}

// loadFilterdnsObjects loads filterdns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filterdnsObjects
//	*filterdnsPrograms
//	*filterdnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFilterdnsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFilterdns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filterdnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsSpecs struct {
	filterdnsProgramSpecs
	filterdnsMapSpecs
	filterdnsVariableSpecs
}

// filterdnsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsProgramSpecs struct {
	XdpFilterDns *ebpf.ProgramSpec `ebpf:"xdp_filter_dns"`
}

// filterdnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsMapSpecs struct {
	ConfigMap     *ebpf.MapSpec `ebpf:"config_map"`
	Ipv4Blacklist *ebpf.MapSpec `ebpf:"ipv4_blacklist"`
	Ipv4Whitelist *ebpf.MapSpec `ebpf:"ipv4_whitelist"`
	Ipv6Blacklist *ebpf.MapSpec `ebpf:"ipv6_blacklist"`
	Ipv6Whitelist *ebpf.MapSpec `ebpf:"ipv6_whitelist"`
	StatsMap      *ebpf.MapSpec `ebpf:"stats_map"`
}

// filterdnsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsVariableSpecs struct {
}

// filterdnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsObjects struct {
	filterdnsPrograms
	filterdnsMaps
	filterdnsVariables
}

func (o *filterdnsObjects) Close() error {
	return _FilterdnsClose(
		&o.filterdnsPrograms,
		&o.filterdnsMaps,
	)
}

// filterdnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsMaps struct {
	ConfigMap     *ebpf.Map `ebpf:"config_map"`
	Ipv4Blacklist *ebpf.Map `ebpf:"ipv4_blacklist"`
	Ipv4Whitelist *ebpf.Map `ebpf:"ipv4_whitelist"`
	Ipv6Blacklist *ebpf.Map `ebpf:"ipv6_blacklist"`
	Ipv6Whitelist *ebpf.Map `ebpf:"ipv6_whitelist"`
	StatsMap      *ebpf.Map `ebpf:"stats_map"`
}

func (m *filterdnsMaps) Close() error {
	return _FilterdnsClose(
		m.ConfigMap,
		m.Ipv4Blacklist,
		m.Ipv4Whitelist,
		m.Ipv6Blacklist,
		m.Ipv6Whitelist,
		m.StatsMap,
	)
}

// filterdnsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsVariables struct {
}

// filterdnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsPrograms struct {
	XdpFilterDns *ebpf.Program `ebpf:"xdp_filter_dns"`
}

func (p *filterdnsPrograms) Close() error {
	return _FilterdnsClose(
		p.XdpFilterDns,
	)
}

func _FilterdnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filterdns_bpfeb.o
var _FilterdnsBytes []byte
