// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package filterdns

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type filterdnsDnsStats struct {
	_              structs.HostLayout
	TotalPackets   uint64
	DnsPackets     uint64
	DroppedPackets uint64
}

// loadFilterdns returns the embedded CollectionSpec for filterdns.
func loadFilterdns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FilterdnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load filterdns: %w", err)
	}

	return spec, err
}

// loadFilterdnsObjects loads filterdns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*filterdnsObjects
//	*filterdnsPrograms
//	*filterdnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFilterdnsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFilterdns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// filterdnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsSpecs struct {
	filterdnsProgramSpecs
	filterdnsMapSpecs
	filterdnsVariableSpecs
}

// filterdnsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsProgramSpecs struct {
	XdpFilterDns *ebpf.ProgramSpec `ebpf:"xdp_filter_dns"`
}

// filterdnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsMapSpecs struct {
	StatsMap *ebpf.MapSpec `ebpf:"stats_map"`
}

// filterdnsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type filterdnsVariableSpecs struct {
}

// filterdnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsObjects struct {
	filterdnsPrograms
	filterdnsMaps
	filterdnsVariables
}

func (o *filterdnsObjects) Close() error {
	return _FilterdnsClose(
		&o.filterdnsPrograms,
		&o.filterdnsMaps,
	)
}

// filterdnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsMaps struct {
	StatsMap *ebpf.Map `ebpf:"stats_map"`
}

func (m *filterdnsMaps) Close() error {
	return _FilterdnsClose(
		m.StatsMap,
	)
}

// filterdnsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsVariables struct {
}

// filterdnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFilterdnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type filterdnsPrograms struct {
	XdpFilterDns *ebpf.Program `ebpf:"xdp_filter_dns"`
}

func (p *filterdnsPrograms) Close() error {
	return _FilterdnsClose(
		p.XdpFilterDns,
	)
}

func _FilterdnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed filterdns_bpfel.o
var _FilterdnsBytes []byte
