// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallBackendServer struct {
	_       structs.HostLayout
	Ip      uint32
	Port    uint16
	Weight  uint8
	Enabled uint8
}

type firewallConnTrack struct {
	_                structs.HostLayout
	ClientIp         uint32
	ClientPort       uint16
	Pad1             uint16
	OriginalDestIp   uint32
	OriginalDestPort uint16
	Pad2             uint16
	TargetIp         uint32
	TargetPort       uint16
	Pad3             uint16
	Timestamp        uint64
}

type firewallDnatRule struct {
	_            structs.HostLayout
	OriginalIp   uint32
	OriginalPort uint16
	Pad1         uint16
	TargetIp     uint32
	TargetPort   uint16
	Protocol     uint8
	Enabled      uint8
}

type firewallFwRule struct {
	_        structs.HostLayout
	IpStart  uint32
	IpEnd    uint32
	Port     uint16
	Protocol uint8
	Action   uint8
}

type firewallFwStats struct {
	_               structs.HostLayout
	TotalPackets    uint64
	AllowedPackets  uint64
	BlockedPackets  uint64
	LvsDnatPackets  uint64
	LvsSnatPackets  uint64
	LvsTotalPackets uint64
}

type firewallServiceConfig struct {
	_            structs.HostLayout
	Vip          uint32
	Vport        uint16
	Protocol     uint8
	Scheduler    uint8
	BackendCount uint32
	Enabled      uint8
	Padding      [3]uint8
}

// loadFirewall returns the embedded CollectionSpec for firewall.
func loadFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewall: %w", err)
	}

	return spec, err
}

// loadFirewallObjects loads firewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallObjects
//	*firewallPrograms
//	*firewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallSpecs struct {
	firewallProgramSpecs
	firewallMapSpecs
	firewallVariableSpecs
}

// firewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallProgramSpecs struct {
	XdpFirewallWithLvs *ebpf.ProgramSpec `ebpf:"xdp_firewall_with_lvs"`
}

// firewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallMapSpecs struct {
	BackendMap    *ebpf.MapSpec `ebpf:"backend_map"`
	BlacklistMap  *ebpf.MapSpec `ebpf:"blacklist_map"`
	ConfigMap     *ebpf.MapSpec `ebpf:"config_map"`
	ConnTrackMap  *ebpf.MapSpec `ebpf:"conn_track_map"`
	DebugCounters *ebpf.MapSpec `ebpf:"debug_counters"`
	DebugMap      *ebpf.MapSpec `ebpf:"debug_map"`
	LvsDnatMap    *ebpf.MapSpec `ebpf:"lvs_dnat_map"`
	ServiceMap    *ebpf.MapSpec `ebpf:"service_map"`
	StatsMap      *ebpf.MapSpec `ebpf:"stats_map"`
	WhitelistMap  *ebpf.MapSpec `ebpf:"whitelist_map"`
}

// firewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallVariableSpecs struct {
}

// firewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallObjects struct {
	firewallPrograms
	firewallMaps
	firewallVariables
}

func (o *firewallObjects) Close() error {
	return _FirewallClose(
		&o.firewallPrograms,
		&o.firewallMaps,
	)
}

// firewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallMaps struct {
	BackendMap    *ebpf.Map `ebpf:"backend_map"`
	BlacklistMap  *ebpf.Map `ebpf:"blacklist_map"`
	ConfigMap     *ebpf.Map `ebpf:"config_map"`
	ConnTrackMap  *ebpf.Map `ebpf:"conn_track_map"`
	DebugCounters *ebpf.Map `ebpf:"debug_counters"`
	DebugMap      *ebpf.Map `ebpf:"debug_map"`
	LvsDnatMap    *ebpf.Map `ebpf:"lvs_dnat_map"`
	ServiceMap    *ebpf.Map `ebpf:"service_map"`
	StatsMap      *ebpf.Map `ebpf:"stats_map"`
	WhitelistMap  *ebpf.Map `ebpf:"whitelist_map"`
}

func (m *firewallMaps) Close() error {
	return _FirewallClose(
		m.BackendMap,
		m.BlacklistMap,
		m.ConfigMap,
		m.ConnTrackMap,
		m.DebugCounters,
		m.DebugMap,
		m.LvsDnatMap,
		m.ServiceMap,
		m.StatsMap,
		m.WhitelistMap,
	)
}

// firewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallVariables struct {
}

// firewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallPrograms struct {
	XdpFirewallWithLvs *ebpf.Program `ebpf:"xdp_firewall_with_lvs"`
}

func (p *firewallPrograms) Close() error {
	return _FirewallClose(
		p.XdpFirewallWithLvs,
	)
}

func _FirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewall_bpfel.o
var _FirewallBytes []byte
